scikit-hep/scikit-hep.github.io

pages/affiliated.md
pages/resources.md

First approach to the affiliated pages.
Should we have bullet points as in projectusers as well or subtitles as the explanation may be larger? @eduardo-rodrigues

Setting up affiliated pages and zfit

---

pages/resources.md

FYI @henryiii, @HDembinski, @jpivarski. Anything else to add?

Add PyHEP 2019 workshop talks

---

pages/funding.md

Hi @jpivarski, @henryiii, @HDembinski, @marinang, I'm starting a page on funding for Scikit-HEP as I have been made aware that this is very important/requested thing at least in the US. I don't see why we should not acknowledge the funds that directly or indirectly make it possible for us to do this work.
Could you kindly have a look and add text/corrections/suggestions as you see fit?
Many thanks.

Add page on funding

---

pages/getting-in-touch.md

Add available StackOverflow tags to getting in touch page

---

pages/documentation.md

Fix issue in package URL for documentation.html

---

_data/projects/statistics/scikit-stats.yml

Fix duplication created with PR https://github.com/scikit-hep/scikit-hep.github.io/pull/25. FYI @marinang.

Delete duplication of info

---

index.md
pages/documentation.md

Sort packages

---

_data/projects/fitting/zfit.yml
_data/projects/histogramming/aghast.yml
_data/projects/manipulation/uproot-methods.yml
_data/projects/misc/scikit-hep-testdata.yml

More Conda-forge badges

---

pages/funding.md

Following @eduardo-rodrigues's request, I've updated the IRIS-HEP funding statement to reflect that I'm also paid 50% to work on IRIS-HEP projects.

Add Feickert to IRIS-HEP funding statement

---

pages/getting-in-touch.md

c.f. https://stackoverflow.com/questions/tagged/pyhf

Add pyhf Stack Overflow tag link

---

_data/projects/interface/pylhe.yml

Add [pylhe](https://github.com/scikit-hep/pylhe) to the list of Scikit-HEP projects

Add pylhe to Scikit-HEP projects

---

pages/developers/packaging.md

Meaningless nitpick PR.
https://scikit-hep.org/pyhf/faq.html#how-is-pyhf-typeset

Use preferred pyhf name formatting

---

pages/developers/index.md

Feel free to extend. Looks a bit better than a TOC only.

Adding a bit of text to the main developer page

---

pages/developers/style.md

More developers info : Flake8 and more MyPy

---

_data/projects/misc/azure-wheel-helpers.yml
_includes/package_table.html
_sass/custom/custom.scss
pages/developers/guidelines.md
pages/developers/index.md
pages/developers/intro.md
pages/developers/packaging.md
pages/developers/style.md

@henryiii, you may remember the discussions we had weeks ago to try and dress a list of requirements and guidelines for the Scikit-HEP packages. I finally tried to turn the discussions into a PR!
The idea would be to have this as a first submenu under https://scikit-hep.org/developer. Some fine-tuning will be needed. Let's try and converge. In particular, some links are likely to be missing, even links to your other pages under https://scikit-hep.org/developer.
Thanks.

Package requirements and guidelines

---

pages/developers/gha_basic.md
pages/developers/style.md

Caching now happens internally, *huge* improvement!

Update for latest version of pre-commit action.

---

pages/developers/gha_basic.md

GHA has added native support for dev versions as of yesterday:
https://github.com/actions/setup-python/issues/20

feat: Support now added for dev Pythons to GHA

---

pages/developers/gha_wheels.md

Reverts scikit-hep/scikit-hep.github.io#70

Revert "Actually use Python 2.7 in win-py27 job"

---

_sass/custom/custom.scss
pages/developers/gha_wheels.md
pages/developers/packaging.md
pages/developers/style.md

Cleans up the presentation a bit, by hiding information that not everyone will need. Adds a mention and details for a very helpful tool (boost-histogram 0.7.0 and 0.10.1 both had extra print statements that shouldn't have been there!).

feat: add folding and flake8-print

---

_config.yml
_sass/color_schemes/skhep.scss
_sass/custom/custom.scss

fix: color for 0.3.x was moved

---

pages/developers/gha_wheels.md

Drop explicit Python version

---

pages/developers/guidelines.md
pages/developers/packaging.md
pages/supported-python-versions.md

Follow up on @HDembinski's suggestion in https://github.com/scikit-hep/pyhf/issues/1075

feat: Clearer mention of python_requires

---

pages/developers/gha_basic.md
pages/developers/gha_pure.md
pages/developers/gha_wheels.md
pages/developers/packaging.md
pages/developers/style.md

Added a section on dependabot, and updated some dependencies. Also fixed a formatting issue.

feat: section on keeping up-to-date

---

pages/projusers.md

See discussions and suggestions at https://github.com/scikit-hep/scikit-hep.github.io/issues/90.

Details on IRIS-HEP project involvement

---

pages/resources.md

Advance thanks for a quick check before this gets merged.

Add Eduardo 2020 presentations

---

pages/developers/gha_basic.md
pages/developers/style.md

Closes #91 . Feel free to add / change / remove bits. :)

feat: add pre-commit.ci recommendation

---

.gitignore
pages/resources.md

Adding a few talks and papers. @eduardo-rodrigues, if this is the link you want for PyHEP 2020, it should be pretty easy to collect the other talks from there.

chore: add some presentations

---

pages/developers/packaging.md
pages/developers/style.md
pages/supported-python-versions.md

Also mirrored in https://github.com/henryiii/cookie/pull/1 
Also touched up python_requires a bit. Rewrapped some lines to 80 chars, so that hides the changes  a little bit. :(

feat: pyupgrade and isort

---

_data/projects/misc/cookie.yml
pages/developers/index.md

Wrote this but forgot to make the PR. :/
This is the bare minimum; eventually I'd like a little banner or something on the dev pages with Cookie in it.

feat: adding Scikit-HEP/cookie

---

pages/resources.md

Closes https://github.com/scikit-hep/scikit-hep.github.io/issues/109.

Mention the org tutorials on the resources page

---

pages/developers/style.md

fix: minor updates

---

_data/projects/basic/hepunits.yml
_data/projects/histogramming/hist.yml
_data/projects/histogramming/histoprint.yml
_data/projects/histogramming/uhi.yml
_data/projects/misc/scikit-hep.yml
_data/projects/statistics/hepstats.yml

Adding some missing conda badges, and histoprint / uhi, which seem to be missing.

feat: add uhi and histoprint

---

_data/projects/particle/decaylanguage.yml
_data/projects/particle/particle.yml

Add Conda-forge badges for Particle and DecayLanguage

---

pages/developers/packaging.md
pages/developers/style.md

style: add setup-cfg-fmt

---

pages/developers/packaging.md

These even get custom icons! See <https://pypi.org/project/vector/>.

docs: add project links

---

index.md

Might be good to highlight this a bit more to make it more discoverable, since it's a major part of our site?

feat: link to developer pages

---

pages/developers/packaging.md
pages/developers/style.md

refactor: version -> _version

---

pages/developers/gha_wheels.md
pages/developers/style.md

Mostly some minor version bumps.

chore: bump versions and use pre-commit.ci name

---

pages/developers/gha_basic.md

Adding more useful info to GHA page.

docs: add more about GHA

---

pages/developers/badges.md
pages/developers/gha_basic.md
pages/developers/gha_pure.md
pages/developers/gha_wheels.md
pages/developers/index.md
pages/developers/mypy.md
pages/developers/nox.md
pages/developers/style.md

Closes #82. Didn't pay much attention to the page order.

feat: page on MyPy

---

pages/developers/mypy.md

This expands the mypy section adding Protocols (which we use in UHI, for example) from my recent PyHEP talk. Also adding a little bit about type narrowing.

docs(mypy): add protocols and type narrowing

---

pages/developers/index.md
pages/developers/pytest.md

feat: page on pytest

---

_data/projects/misc/pybind11.yml

I think we should probably list this as well given we have quite a few projects depending on it, and we have maintainers on the team.

feat: include pybind11 as an affiliated project

---

pages/developers/gha_wheels.md

Removes old comments about Python 2 and the Windows Python 2 job (yuck).

chore: bump to cibuildwheel 2

---

pages/developers/pytest.md
pages/developers/style.md

Created entirely from the GItHub "." editor online. :)

chore: minor additions

---

_data/projects/interface/pyjet.yml

Related to https://github.com/scikit-hep/pyjet/pull/56.

Tag pyjet as deprecated

---

pages/developers/style.md

Linked: https://github.com/scikit-hep/cookie/pull/38

feat: add pycln as a recommendation

---

pages/developers/packaging.md
pages/developers/pep621.md

In honor of Flit joining the PyPA, here's a new version of our setup for pure Python projects.

feat: pep 621 page, flit

---

pages/developers/style.md

feat: mention isort + pyupgrade + 3.7

---

.gitignore
noxfile.py
pages/developers/style.md

feat: easier pre-commit version bumping

---

pages/developers/style.md

This can be noisy, but can also be very powerful in cleaning up and finding issues.

feat: add pylint

---

.pre-commit-config.yaml
_includes/head.html

Mirrored from https://github.com/iris-hep/iris-hep.github.io-source/pull/1283

chore: disallow misnamed data files, tabs, crlf

---

pages/about/faq.md
pages/about/index.md

Fixes https://github.com/scikit-hep/scikit-hep.github.io/issues/187.

Add explanation of what HEP is

---

pages/developers/style.md

X-ref: https://github.com/scikit-hep/cookie/pull/77

fix: use all flag instead of config for pycln

---

pages/developers/pep621.md

X-ref [#72](https://github.com/scikit-hep/cookie/pull/72)

chore: use main setuptools branch

---

pages/developers/style.md

See https://github.com/psf/black/issues/2964 for details.

style: bump black

---

Gemfile
Gemfile.lock
_includes/head_custom.html
_includes/interactive_repo_review.html
assets/js/webapp.js
pages/developers/index.md
pages/developers/repo_review.md

This adds scikit-hep-repo-review inline in our developer pages. You can see the full tool here: https://henryiii.github.io/scikit-hep-repo-review/.

feat: repo review tool

---

.pre-commit-config.yaml
pages/projusers/publications.md
pages/resources.md

- Presentations at PyHEP 2021
- Conference proceedings
- PhD theses
- arXiv articles
- Many old presentations

Add more presentations on, and publications using, org packages

---

pages/developers/gha_wheels.md
pages/developers/index.md
pages/developers/intro.md
pages/developers/nox.md
pages/developers/packaging.md
pages/developers/pep621.md
pages/developers/pytest.md
pages/developers/repo_review.md
pages/developers/style.md

Several small things noticed on read through. Partially addressing #200 as well.

chore: add minor updates

---

_sass/custom/custom.scss
assets/js/webapp.js
pages/developers/pep621.md
pages/developers/style.md

Pulling the functional change from #218 as well, just to keep that one an addition only (and to get this in quicker).
- chore: webapp 0.3.0
- feat: support selecting tabs when linking
- fix: better expanders

feat: link directly, better dropdowns

---

pages/developers/badges.md

Add tabbed structure from the [Simple Python packaging](https://scikit-hep.org/developer/pep621) page to the [Badges](https://scikit-hep.org/badges) page

feat: add tabs to the Badges page

---

pages/developers/pep621.md

See https://github.com/scikit-hep/cookie/discussions/87.

docs: recommend hatch(ling)

---

noxfile.py
pages/developers/style.md

fix: Version 2 of setup-cfg-fmt requires a new flag

---

pages/developers/gha_basic.md

This was added about a week ago, and we've used it a couple of places. Adding a bit of a guide in an expandable section.

feat: add description of how to use the new Pages

---

_includes/head_custom.html
assets/js/webapp.js

Fixes the dependabot recommendation, adds one check, and uses Pyodide 0.21.0.

chore: bump repo review

---

pages/packages/documentation.md

fix: formatting issue

---

pages/packages/documentation.md

Fixing https://github.com/scikit-hep/scikit-hep.github.io/issues/258 for real this time! Looks like sticking a comment at the beginning of a line breaks table formatting.

fix: table formatting correction

---

pages/user/resources.md

Hi @lovaslin, I noticed these publications on your package and am adding them.
In the future do not forget to update the site for what concerns you ... In that respect, are there any presentations on pyBumpHunter that you should add, or papers/proceedings/... that cite your package? Kindly make a PR to get in the info in, which is very important.
Advance thanks.

Add publications on pyBumpHunter

---

pages/user/resources.md

FYI @henryiii, @HDembinski, @matthewfeickert, @jpivarski, etc.
I do updates every now and then but it is time consuming and it would be nicer if we all update the site with our talks every now and then ;-). Kindly have that in mind for the future - we are all maintainers of the site.

Update April-Nov 2022 of Scikit-HEP presentations

---

pages/news.md

Anything else you @jpivarski would like to add?

docs: add news on major releases awkward 2.0.0 and uproot 5.0.0

---

_data/projects/interface/numpythia.yml

* c.f. https://github.com/scikit-hep/numpythia
Follows up on https://github.com/scikit-hep/numpythia/issues/74 which was resolved by @eduardo-rodrigues. :+1:

feat: Deprecate numpythia as archived

---

pages/projusers/publications.md

Indeed some arXiv articles got published in the meantime, and I did a little clean-up.

docs: Update of publications using org packages

---

pages/developers/style.md

We've been moving over to Ruff, such as in Awkward, scikit-build-core, Hist, cibuildwheel, and build, so making the move here.

feat: move to using Ruff

---

noxfile.py
pages/developers/style.md

- fix: pre-commit bump was not matching some entries
- chore: bump pre-commit

fix: noxfile pre-commit bump

---

pages/developers/style.md

fix: order setuptools checks together

---

pages/developers/style.md

chore: minor adjustment to Ruff

---

pages/developers/style.md

Moved to own section, and added nbqa.

feat: section for notebook support

---

pages/developers/pep621.md

X-ref: https://github.com/pypa/packaging.python.org/pull/1220

chore: update name of PDM backend

---

pages/developers/mypy.md

Adding some help for runtime annotation usage & some updates for 3.7+ min.

fix: minor updates to mypy page

---

assets/js/tabs.js
pages/developers/gha_pure.md
pages/developers/gha_wheels.md
pages/developers/pep621.md

This became publicly available a couple of days ago.

feat: include oidc auth in tab

---

_includes/head_custom.html

chore: add Plausible stats counter

---

pages/news.md

This indeed seemed like something we ought to say in the news, 'cause it's really nice.

News - org packages taught in HSF Training WG events

---

_data/projects/basic/ragged.yml
_data/projects/manipulation/hepconvert.yml
pages/news.md

News and list update -hepconvert and ragged packages joined org

---

pages/projusers/projects.md

Hi @jonas-eschle, I noticed that the zfit link was outdated. I will merged this straightaway but feel free to submit an update to the text if you fancy. Advance thanks.

Update of projects using Scikit-HEP

---

.readthedocs.yaml

ci: add a readthedocs config

---

pages/packages/qr_codes.md

fix: relative urls for qrcodes

---

pages/news.md

Thank you Scientific Python ❤️ !

News - Scikit-HEP integrates the Scientific Python Ecosystem Coordination Core Projects as a domain stack

---

pages/news.md

Hello @henryiii and @jonas-eschle, I believe these are the 2 obvious pieces of news missing. Check and let me know if you see other news worth adding. Thanks.

News update

---

_data/projects/ml/NNDrone.yml
pages/news.md

FYI @kgizdov, @matthewfeickert and @jonas-eschle, since involved in this.

Package NNDrone is deprecated

---

pages/projusers/publications.md

FYI @APN-Pucky and @matthewfeickert.

Add recent publications citing pylhe

---

pages/user/resources.md

Add old podcast from Henry
