- _data/projects/statistics/pyhf.yml
Add [pyhf](https://github.com/scikit-hep/pyhf) to list of ~~scikit-hep~~ Scikit-HEP projects under "statistics" (as I didn't think it was worth making a separate category for "probabilistic modeling" at the moment).
cc @kratsg @lukasheinrich
> Add pyhf to listed projects

- _data/projects/statistics/pyhf.yml
Adds the proper link to the https://scikit-hep.org/documentation page
> Add docs webpage to pyhf entry

- _data/projects/basic/awkward-array.yml
- _data/projects/basic/hepunits.yml
- _data/projects/fitting/goofit.yml
- _data/projects/fitting/iminuit.yml
- _data/projects/fitting/probfit.yml
- _data/projects/fitting/zfit.yml
- _data/projects/histogramming/aghast.yml
- _data/projects/histogramming/boost-histogram.yml
- _data/projects/histogramming/histbook.yml
- _data/projects/interface/numpythia.yml
- _data/projects/interface/pyhepmc.yml
- _data/projects/interface/pyjet.yml
- _data/projects/manipulation/formulate.yml
- _data/projects/manipulation/root-numpy.yml
- _data/projects/manipulation/root-pandas.yml
- _data/projects/manipulation/uproot-methods.yml
- _data/projects/manipulation/uproot.yml
- _data/projects/misc/conda-forge-root.yml
- _data/projects/misc/scikit-hep-testdata.yml
- _data/projects/misc/scikit-hep.yml
- _data/projects/particle/decaylanguage.yml
- _data/projects/particle/particle.yml
- _data/projects/statistics/hepstats.yml
- _data/projects/statistics/pyhf.yml
- _data/projects/visualization/mplhep.yml
- _data/projects/visualization/vegascope.yml
- _sass/custom/custom.scss
- index.md
Styling changed on the front page, and added project badges. Example:
I could add Python version, Wheel available, and/or project status if we properly supported those across all projects.
> Restyle and add badges

- _data/projects/fitting/goofit.yml
- index.md
- pages/affiliated.md
The conda forge link for GooFit was broken, and in fixing that I realized all Conda-forge links were broken. This fixes them.
> Fixing Conda-forge links

- _data/projects/fitting/iminuit.yml
As iminuit is a Scikit-HEP package, and no longer just affiliated, then it should be updated on the pages as well.
> Promote iminuit from affiliated

- pages/developers/gha_basic.md
Basis for hepunits 1.2.0.
Had to revert to checkout/v1 due to issue with checkout/v2: https://github.com/actions/checkout/issues/249 .
> Adding page on setting up GHA

- pages/developers/gha_wheels.md
This PR adds a description for building binary wheels via [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) for the Scikit-HEP developers (and anyone else who is interested). This completes the initial phase for the guidelines for Scikit-HEP developers that has been in progress for quite some time. This is the sequel to the page here: https://scikit-hep.org/developer/gha_basic .
I'd like to deprecate azure-wheel-helpers and move the Scikit-HEP builds over to cibuildwheel. It's a well maintained, popular library that supports all backends (GHA, Azure, Travis, Appveyor, CircleCI). GHA is easier to automate on tags/releases, and doesn't require separate authentication / permissions setup. It also doesn't require any GUI setup, other than loading the secret. I have been watching …
> Full wheel support

- _data/projects/misc/azure-wheel-helpers.yml
Need to make sure markdown is valid here. Edit: yes, it is. ✅
> Deprecate azure-wheel-helpers in favor of cibuildwheel.

- pages/developers/gha_basic.md
- pages/developers/gha_wheels.md
> Since GHA does not have manual triggers,
@matthewfeickert found the post, released by GitHub yesterday, now they do!
> feat: Add workflow dispatch to CI!

- _includes/nav.html
- _sass/custom/custom.scss
- pages/developers/badges.md
- pages/developers/gha_basic.md
- pages/developers/gha_pure.md
- pages/developers/gha_wheels.md
- pages/developers/guidelines.md
- pages/developers/index.md
This PR:
* Breaks up the GHA into better sections: intro (basic testing), pure Python wheels, and binary wheels. Some updates for recent improvements / experience.
* Makes the menu a little better (it seems to have changed recently, but don't see a commit for a change)
* Shortens a few menu items so it's easier to navigate.
* Adds a bit of text and crosslinks to the main developer page.
> Break up GHA

- _data/projects/statistics/pyhf.yml
Add the Conda-forge badge for `pyhf` and update the README link to reflect that `pyhf` now used RST.
> docs: Add pyhf Conda-forge badge

- _includes/package_table.html
The home page is long enough that it would be useful to be able to link specifically to a place on it.
> feat: support hyperlinks on homepage package list

- pages/developers/gha_pure.md
- pages/developers/gha_wheels.md
This adds a recipe that can be copied verbatim into projects that otherwise follow the guidelines to setup a pure-python publish step.
> docs: recipe for publishing

- pages/developers/gha_basic.md
- pages/developers/gha_pure.md
- pages/developers/gha_wheels.md
This has now been accepted by the Python Packaging Authority, so let's make it the main recommendation, as we stated we would.
> fix: change recommendation to PyPA-Build

- _data/projects/basic/awkward-array.yml
- _data/projects/manipulation/uproot-methods.yml
- _data/projects/manipulation/uproot.yml
Awkward is still the old one on conda-forge, but I guess it's supposed to be in the same place? CC @JPivarski.
> fix: update awkward links

- pages/developers/packaging.md
Brought up on Slack (can't pull up details, Slack is down currently).
Adds MANIFEST.in help, along with a few more notes and some helpful links. `include_package_data` was missing, as well.
A new and exiting addition to Scikit-HEP related to all this has been in the works during the holidays, and should come along soon, but this should help in the meantime.
> feat: add MANIFEST.in and more help

- pages/developers/gha_pure.md
- pages/developers/gha_wheels.md
- pages/developers/style.md
Updating cibuildwheel to 1.8.0, which includes Arch emulation! Also using pipx to run build and twine, since it's installed by default on the GHA runners and it's the right tool to use for applications (pip is for importable libraries). Also fixes a typo with the black version, and bumps a few things. MyPy 0.800 is out, but the pre-commit mirror hasn't updated yet.
> chore: updating cibw

- pages/developers/packaging.md
`packaging.python.org` has been accepting our contributions to bring their tutorials up to date; so this statement is becoming less true; time to remove it!
> fix: extra link to packaging

- pages/supported-python-versions.md
Rewriting the Python support statement to better indicate the death of Python 2, and to highlight the 3.6 discrepancy we currently have with NEP 29 and why it's there. Also adds a note about `universal=True`.
Will need sign offs or feedback from several @scikit-hep devs since it's a community statement.
> feat: rewrite Python support statement

- _data/projects/manipulation/root-numpy.yml
- _data/projects/manipulation/root-pandas.yml
Given [the discussion on Gitter](https://gitter.im/Scikit-HEP/community?at=60550684f07ffa1eb551d253) mark `root_numpy` and `root-pandas` as deprecated.
> chore: Note root_numpy and root-pandas are deprecated

- pages/developers/gha_wheels.md
Shouldn't we use the "latest" of the OS instead?
and a small typo fix
> Fix typo and use latest os

- pages/developers/gha_pure.md
- pages/developers/gha_wheels.md
This was implemented in pipxproject/pipx#615 and pypa/build#247, and the GitHub Actions runners have been updated to the latest pipx, so this now works with the simpler syntax. Matching Cookie PR: scikit-hep/cookie#11
> chore: use newer pipx run syntax

- pages/developers/packaging.md
Resolves #130 
`prune *` does not fully remove _all_ files, but `prune **` will.
For reference, c.f. https://github.com/scikit-hep/pyhf/pull/1449
> fix: Revise prune strategy for MANIFEST.in to properly remove all

- pages/developers/packaging.md
- pages/developers/style.md
Use pyproject.toml as the canonical location for all config (except flake8), and simplify.
Also see https://github.com/scikit-hep/cookie/pull/18
> feat: use pyproject.toml more consistently

- pages/developers/nox.md
This adds a basic page on using nox. I'd like to start gently suggesting packages provide noxfiles. This is not yet a perfect fit for every package, and should not replace a well designed CI file, but it's great for new contributors, and for "fly-by" contributors like me who tend to jump from package to package, and for specialized tasks that tend to not be run often.
View here: https://github.com/scikit-hep/scikit-hep.github.io/blob/henryiii/feat/nox/pages/developers/nox.md
> feat: add page on Nox

- _includes/package_table.html
- index.md
- pages/packages/index.md
This makes the front page cleaner, avoiding showing a bunch of deprecated red items on first visit.
> fix: remove deprecated projects from the main page

- pages/developers/style.md
New version of LLVM today, new version of clang-format wheels & hook today.
> chore: bump LLVM

- _data/projects/misc/conda-forge-root.yml
- pages/developers/gha_basic.md
- pages/developers/nox.md
- pages/developers/packaging.md
- pages/developers/pep621.md
- pages/developers/style.md
- pages/supported-python-versions.md
Python 3.6 hit EOL today! New users should at least be on 3.7, so let's update the examples.
Also updated the cookie https://github.com/scikit-hep/cookie/pull/63
> chore: use Python 3.7+ for examples

- noxfile.py
- pages/developers/style.md
I finally can remove the `--pre` to `lastversion` due to a non-beta Black release!
Also reworked the update script a bit to get the version check and version bump messages closer together.
> chore: improve and run bump script, new Black

- pages/developers/nox.md
- pages/developers/pep621.md
Probably should add tabs here if I'm trying to get it into packaging.python.org in https://github.com/pypa/packaging.python.org/pull/1031 . :)
- chore: mention color workaround
- feat: include multiple backends
> feat: add tabs for other PEP 621 backends

- pages/developers/style.md
Bump versions via `nox -s bump`, and address https://github.com/pre-commit/mirrors-clang-format/pull/10 by listing an explicit `types_or`.
> chore: bump pre-commit and add types_or

- pages/projusers/publications.md
- pages/resources.md
FYI @matthewfeickert  - https://scikit-hep.org/resources is getting close to up-to-date.
> Add presentations on pyhf and articles citing it

- _includes/toc.html
- _sass/custom/custom.scss
- pages/developers/intro.md
Cleaning up visuals a bit, expandable boxes are more obvious, especially when expanded.
> fix: minor styling on details boxes

- pages/installing-packages.md
- pages/user/index.md
- pages/user/installing-conda.md
This is a question that @eduardo-rodrigues, @henryiii, @chrisburr, @HDembinski may want to weigh in on: whether we, as Scikit-HEP, should endorse Miniforge as the recommended way to install Python packages. I know that we have different preferences, but in my experience with tutoring, getting users started has been easiest with a conda environment, and now Miniforge even removes the aspect of having to change channels and be sure that conda-forge doesn't get mixed in with the default channel.
I was prompted to make this pull request by a [conversation on Slack](https://iris-hep.slack.com/archives/CFEK2FECR/p1652371587328839) (link will only work if you're on IRIS-HEP's Slack). The people involved in that conversation were @alexander-held, @kpedro88, @Moelf, @matthewfeickert, @agoose77, …
> Add Miniforge instructions for users

- pages/developers/gha_basic.md
This was incorrectly updated; setup-python v4 breaks "simple" usage and always requires a `python-version` now. For now, let's add the manual setting unless https://github.com/actions/setup-python/issues/421 ends up re-adding a default (which I'd really love to see, as this was handy and much simpler).
> fix: correcting usage of setup-python

- pages/developers/style.md
Resolves #227
* Update pre-commit/pre-commit-hooks example to v4.3.0
* Add the 'name-tests-test' pre-commit hooks which verifies that test files under `tests/` conform to `pytest` naming conventions.
- Use the `--pytest-test-first` option to match the `test_.*\.py` naming convention.
> feat: Add 'name-tests-test' to pre-commit hooks example

- pages/developers/gha_basic.md
It is no longer required to specify dependabot ignore official action minor/patch versions, as it now keeps the style you are using. Also improving the specification of cancellation.
> chore: update actions/dependabot

- pages/user/installing-conda.md
I was hoping I wouldn't have to do this, but https://github.com/mamba-org/mamba/issues/1706 has been open for a while. I'll keep an eye on it (because it makes updating harder for _me_, too) so that we can remove this box as soon as this issue gets fixed.
I believe that this change is ready for review.
> Insert warning about broken conda in user installation guide.

- pages/developers/badges.md
> fix: get rid of uneven line breaks in `badges.md`

- pages/user/installing-conda.md
mamba-org/mamba#1706 has been resolved and we can remove the warning about it now. This is great because it presents a much simpler story to the target audience of this page (Python beginners).
It directly reverts #239, just removing the warning box.
> Remove warning about broken conda in user installation guide. (Reverts #239.)

- pages/projusers/publications.md
* Add pyhf use citation from 'Search for Events with Two Displaced Vertices from
Pair-Produced Neutral Long-Lived Particles Decaying to Hadronic Jets in the
Muon Spectrometer of the ATLAS Detector with Full Run 2 Data'.
- c.f. https://inspirehep.net/literature/2086276
- c.f. https://cds.cern.ch/record/2812260
- Ph.D. dissertation of Audrey Kvam
* Add pyhf use citation from 'Search for pair production of Higgs Bosons
decaying to four bottom quarks with data collected by the ATLAS detector'.
- c.f. https://inspirehep.net/literature/2085649
- c.f. https://cds.cern.ch/record/2812193
- Ph.D. dissertation of Lucas Santiago Borgna
* Add pyhf use citation from 'Signal region combination with full and simplified
likelihoods in MadAnalysis 5'.
- c.f. https://inspirehep.net/literature/2103971
* Add …
> feat: Add pyhf July 2022 use citations

- pages/projusers/publications.md
FYI @HDembinski, @henryiii and @jpivarski, I found the first citations of `pyhepmc` and `Vector` :-).
> Add more use citations - Scikit-HEP, pylhe, etc.

- pages/developers/badges.md
- pages/developers/coverage.md
This was long due!
The "Coverage for projects written in Python and C++" section is empty right now, and I think it would be better if someone experienced could write that section. I have never done any coverage stuff on projects using Python and C++, but I can take up a more days and learn it on a dummy project.
cc: @henryiii @amangoel185
> feat: add a developers page on coverage and codecov

- pages/developers/packaging.md
- pages/developers/pep621.md
Supported since `setuptools_scm` 7, Python 3.7+ only.
> feat: add git archive support for auto versioning

- pages/developers/coverage.md
- pages/developers/intro.md
- pages/developers/pytest.md
We have two items in the "order 4" slot.
> fix: page order incorrect when testing just-the-docs 0.4.0 RC

- _data/projects/histogramming/aghast.yml
* c.f. https://github.com/scikit-hep/aghast
Following up on [this Gitter discussion](https://gitter.im/Scikit-HEP/community?at=6357ea04aa210536d62a0105).
Closes #280.
> feat: Deprecate aghast as no longer supported or maintained

- pages/news.md
* pyhf was accepted as an Affiliated Project of NumFOCUS in December 2022.
- c.f. https://github.com/pyhf/numfocus-affiliate-project-application/pull/2
* pyjet was archived in January 2023.
- c.f. https://github.com/scikit-hep/pyjet/pull/84
> feat: Add pyhf NumFOCUS affiliated project and pyjet archive news

- pages/projusers/publications.md
Adds and updates the pylhe citations listed in https://github.com/scikit-hep/pylhe/issues/181 that are not already listed on the Scikit-HEP publication page.
* Probing compressed higgsinos with forward protons at the LHC
- c.f. https://inspirehep.net/literature/2140007
* MadMiner: Machine learning-based inference for particle physics
- c.f. https://inspirehep.net/literature/1746275
* Benchmarking simplified template cross sections in WH production
- c.f. https://inspirehep.net/literature/1750323
* Photon collider search strategy for sleptons and dark matter at the LHC
- c.f. https://inspirehep.net/literature/1703804
> feat: Update citations for pylhe through 2022

- pages/developers/style.md
Ruff doesn't seem to treat B9xx specially, so this doesn't do anything.
> fix: drop explicit B9 addition

- pages/developers/pep621.md
This is not even used by some backends, and is not the correct way to set a standard license, it's only for modified licenses. Standard ones must be specified via classifiers.
> fix: remove license setting

- pages/projusers/publications.md
Add `pylhe` use citation from [On the BSM reach of four top production at the LHC](https://inspirehep.net/literature/2633019) by Anisha, Oliver Atkinson, Akanksha Bhardwaj, Christoph Englert, Wrishik Naskar, Panagiotis Stylianou.
This was noticed by @lukasheinrich over in https://github.com/scikit-hep/pylhe/issues/181#issuecomment-1509207141.
> docs: Add pylhe use citation from BSM reach of four top production at LHC paper

- _config.yml
0.5.0 breaks us. I think it might be due the base-url being unset. ~~I might try that first.~~ We don't have a baseurl on `scikit-hep.org`, so don't think there's something I can set here.
> fix: issue with latest just-the-docs

- pages/news.md
* awkward was accepted as an Affiliated Project of NumFOCUS in March 2023.
@jpivarski, @matthewfeickert, can you confirm the date?
> News - awkward accepted as an affiliated project of NumFOCUS

- pages/user/installing-conda.md
Now that mamba has been absorbed into mainline conda, the installation instructions can be simpler. I noticed this while trying to get students started: I don't want to have to say, "ignore all the mamba stuff," as that just makes it more complicated.
I also added a CUDA section as a drop-down. We're not even close to having simple recipes that anyone can follow to install packages that depend on CUDA, but at least we can get them started with some pointers. For instance, it's helpful to let people know that CUDA itself (at the time of this writing) cannot be installed as a conda package. (The packages that claim to do this are _not_ robust.)
> docs: update conda best practices

- .pre-commit-config.yaml
- _includes/head.html
- _sass/color_schemes/darkskhep.scss
- assets/css/just-the-docs-darkskhep.scss
- assets/css/just-the-docs-skhep.scss
Link color was not being set, since we were overriding the theme setting infrustructure to get light/dark mode switching. I've followed https://just-the-docs.com/docs/customization/#define-a-custom-scheme and integrated the theme color setting with our custom infrustructure.
> fix: link color issue
